# This file contains configuration for running e2e tests.
# Many of these fields can be overridden with environment variables.
# All fields that support this have the corresponding environment variable name in a comment beside the field.

---
chains:
  # the entry at index 0 corresponds to CHAIN_A
- chainId: chainA-1
  numValidators: 1
  numFullNodes: 0
  image: ghcr.io/cosmos/ibc-go-simd # override with CHAIN_IMAGE
  tag: main # override with CHAIN_A_TAG
  binary: simd # override with CHAIN_BINARY

  # the entry at index 1 corresponds to CHAIN_B
- chainId: chainB-1
  numValidators: 1
  numFullNodes: 0
  image: ghcr.io/cosmos/ibc-go-simd # override with CHAIN_IMAGE
  tag: main # override with CHAIN_B_TAG
  binary: simd # override with CHAIN_BINARY

activeRelayer: hermes # override with RELAYER_ID
relayers:
  - id: hermes
    image: ghcr.io/informalsystems/hermes
    tag: "v1.7.0"
  - id: rly
    image: ghcr.io/cosmos/relayer
    tag: "latest"
  - id: hyperspace
    image: ghcr.io/misko9/hyperspace
    tag: "timeout"

cometbft:
  logLevel: info

debug:
  # setting this value to true will force log collection even if the test passes.
  dumpLogs: false

# Required only for upgrade tests.
# Chain A will be upgraded the specified tag.
# The plan name must be registered as an upgrade handler in the given tag.
upgrade:
  planName: ""
  tag: ""
