name: Capability Module
# This workflow runs when a PR is opened that targets code that is part of the capability module.
on:
  pull_request:
    paths:
      - '.github/workflows/capability.yml'
      - 'modules/capability/**'
      - 'proto/capability/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ['amd64', 'arm', 'arm64']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build capability-module
        run: |
          cd modules/capability
          GOARCH=${{ matrix.go-arch }} go build ./...

  tests:
    if: github.event.pull_request.head.repo.fork == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Go Test
        run: |
          cd modules/capability
          go test -v -mod=readonly ./...
      - name: sonarcloud
        if: ${{ env.GIT_DIFF && !github.event.pull_request.draft && env.SONAR_TOKEN != null }}
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: modules/capability/
